export const contributors = [
            {
                repo: '贡献人员',
                list: [
  {
    "login": "wxize",
    "id": 12660172,
    "node_id": "MDQ6VXNlcjEyNjYwMTcy",
    "avatar_url": "https://avatars.githubusercontent.com/u/12660172?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/wxize",
    "html_url": "https://github.com/wxize",
    "followers_url": "https://api.github.com/users/wxize/followers",
    "following_url": "https://api.github.com/users/wxize/following{/other_user}",
    "gists_url": "https://api.github.com/users/wxize/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/wxize/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/wxize/subscriptions",
    "organizations_url": "https://api.github.com/users/wxize/orgs",
    "repos_url": "https://api.github.com/users/wxize/repos",
    "events_url": "https://api.github.com/users/wxize/events{/privacy}",
    "received_events_url": "https://api.github.com/users/wxize/received_events",
    "type": "User",
    "site_admin": false,
    "contributions": 10
  },
  {
    "login": "vilex",
    "id": 18087205,
    "node_id": "MDQ6VXNlcjE4MDg3MjA1",
    "avatar_url": "https://avatars.githubusercontent.com/u/18087205?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/vilex",
    "html_url": "https://github.com/vilex",
    "followers_url": "https://api.github.com/users/vilex/followers",
    "following_url": "https://api.github.com/users/vilex/following{/other_user}",
    "gists_url": "https://api.github.com/users/vilex/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/vilex/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/vilex/subscriptions",
    "organizations_url": "https://api.github.com/users/vilex/orgs",
    "repos_url": "https://api.github.com/users/vilex/repos",
    "events_url": "https://api.github.com/users/vilex/events{/privacy}",
    "received_events_url": "https://api.github.com/users/vilex/received_events",
    "type": "User",
    "site_admin": false,
    "contributions": 5
  },
  {
    "login": "jscc",
    "id": 17757477,
    "node_id": "MDQ6VXNlcjE3NzU3NDc3",
    "avatar_url": "https://avatars.githubusercontent.com/u/17757477?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/jscc",
    "html_url": "https://github.com/jscc",
    "followers_url": "https://api.github.com/users/jscc/followers",
    "following_url": "https://api.github.com/users/jscc/following{/other_user}",
    "gists_url": "https://api.github.com/users/jscc/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/jscc/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/jscc/subscriptions",
    "organizations_url": "https://api.github.com/users/jscc/orgs",
    "repos_url": "https://api.github.com/users/jscc/repos",
    "events_url": "https://api.github.com/users/jscc/events{/privacy}",
    "received_events_url": "https://api.github.com/users/jscc/received_events",
    "type": "User",
    "site_admin": false,
    "contributions": 3
  },
  {
    "login": "vilex",
    "id": 18087205,
    "node_id": "MDQ6VXNlcjE4MDg3MjA1",
    "avatar_url": "https://avatars.githubusercontent.com/u/18087205?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/vilex",
    "html_url": "https://github.com/vilex",
    "followers_url": "https://api.github.com/users/vilex/followers",
    "following_url": "https://api.github.com/users/vilex/following{/other_user}",
    "gists_url": "https://api.github.com/users/vilex/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/vilex/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/vilex/subscriptions",
    "organizations_url": "https://api.github.com/users/vilex/orgs",
    "repos_url": "https://api.github.com/users/vilex/repos",
    "events_url": "https://api.github.com/users/vilex/events{/privacy}",
    "received_events_url": "https://api.github.com/users/vilex/received_events",
    "type": "User",
    "site_admin": false,
    "contributions": 2
  },
  {
    "login": "wxize",
    "id": 12660172,
    "node_id": "MDQ6VXNlcjEyNjYwMTcy",
    "avatar_url": "https://avatars.githubusercontent.com/u/12660172?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/wxize",
    "html_url": "https://github.com/wxize",
    "followers_url": "https://api.github.com/users/wxize/followers",
    "following_url": "https://api.github.com/users/wxize/following{/other_user}",
    "gists_url": "https://api.github.com/users/wxize/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/wxize/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/wxize/subscriptions",
    "organizations_url": "https://api.github.com/users/wxize/orgs",
    "repos_url": "https://api.github.com/users/wxize/repos",
    "events_url": "https://api.github.com/users/wxize/events{/privacy}",
    "received_events_url": "https://api.github.com/users/wxize/received_events",
    "type": "User",
    "site_admin": false,
    "contributions": 1
  },
  {
    "login": "SonyZ2",
    "id": 26398552,
    "node_id": "MDQ6VXNlcjI2Mzk4NTUy",
    "avatar_url": "https://avatars.githubusercontent.com/u/26398552?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/SonyZ2",
    "html_url": "https://github.com/SonyZ2",
    "followers_url": "https://api.github.com/users/SonyZ2/followers",
    "following_url": "https://api.github.com/users/SonyZ2/following{/other_user}",
    "gists_url": "https://api.github.com/users/SonyZ2/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/SonyZ2/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/SonyZ2/subscriptions",
    "organizations_url": "https://api.github.com/users/SonyZ2/orgs",
    "repos_url": "https://api.github.com/users/SonyZ2/repos",
    "events_url": "https://api.github.com/users/SonyZ2/events{/privacy}",
    "received_events_url": "https://api.github.com/users/SonyZ2/received_events",
    "type": "User",
    "site_admin": false,
    "contributions": 1
  }
]
            }
        ]